language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli bower
install: npm install
notifications:
  email: false
deploy:
  provider: heroku
  app: tonal-starfield
  api_key:
    secure: UCaaf2nh4My7e6yT5h4yqLlOwjyio5cT0BGOjlqZK2s3TAyivD++wHoHMJDVmdgxWOkVrpQC9f0VjCvbfMfyOHiOM6rauoa/nRK36Hi5Tl4yR8usZqLX7dbxBFflQ8L4iu8TFnHJy96+sFCtcunn1UzyslrtsYsCOPwQdC1sKow=
