language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli bower
install: npm install
notifications:
  email: false
deploy:
  provider: heroku
  app: tonal-starfield
  api_key:
    secure: gutw7F2S5ozg/J+URi9CRAInQHknNpwpepOUukikVddWkJo5cXngTEmhDJUVRDXcodafyl/OFzF9EFxrCEs8Aexju0kxhtUo+FUZ/S1EjdKuSOUPlex/055daryKcMKZLDZS0PJluPf8EJy1cJ/lwUGA8GNTYwZUXjx8so0fvCM=
