language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli bower
install: npm install
notifications:
  email: false
deploy:
  provider: heroku
  app: tonal-starfield
  api_key:
    secure: Hf7gYAeS6iRVGCNwVFB2q/paRNTWYsgdCMOTAfLh4vhbGmcBXkfawcIg1iuBe2qhtLRADhOrwt01IV7dGfNu5Qo07/kDN0eMfzSBDL6q5eHYRiJZY7LCFPPRN1Bf8z1awbT9vdi2o6kjIrV1yfFwkJlAwvDsjs2vEh64Jed1L7g=
